<Project>
  <PropertyGroup>
    <SoftwareOutputRoot>H:\Software Output Directory</SoftwareOutputRoot>
    <BuildEnvironmentName Condition="'$(Configuration)' == 'Release'">正式环境</BuildEnvironmentName>
    <BuildEnvironmentName Condition="'$(Configuration)' == 'Debug'">测试环境</BuildEnvironmentName>
    <BuildEnvironmentName Condition="'$(BuildEnvironmentName)' == ''">$(Configuration)</BuildEnvironmentName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>
</Project>
