//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareModularWorkflow.Lang.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HardwareModularWorkflow.Lang.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware Modular Workflow 的本地化字符串。
        /// </summary>
        public static string About_ApplicationName {
            get {
                return ResourceManager.GetString("About_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A hardware-centric modular workflow automation platform. 的本地化字符串。
        /// </summary>
        public static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings are saved to app_settings.json in the application directory. 的本地化字符串。
        /// </summary>
        public static string About_SettingsLocation {
            get {
                return ResourceManager.GetString("About_SettingsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Definition 的本地化字符串。
        /// </summary>
        public static string Button_AddDefinition {
            get {
                return ResourceManager.GetString("Button_AddDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Module 的本地化字符串。
        /// </summary>
        public static string Button_AddModule {
            get {
                return ResourceManager.GetString("Button_AddModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Step 的本地化字符串。
        /// </summary>
        public static string Button_AddStep {
            get {
                return ResourceManager.GetString("Button_AddStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Sub-Flow 的本地化字符串。
        /// </summary>
        public static string Button_AddSubFlow {
            get {
                return ResourceManager.GetString("Button_AddSubFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Workflow 的本地化字符串。
        /// </summary>
        public static string Button_AddWorkflow {
            get {
                return ResourceManager.GetString("Button_AddWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel All 的本地化字符串。
        /// </summary>
        public static string Button_CancelAll {
            get {
                return ResourceManager.GetString("Button_CancelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string Button_Clear {
            get {
                return ResourceManager.GetString("Button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Logs 的本地化字符串。
        /// </summary>
        public static string Button_ClearLogs {
            get {
                return ResourceManager.GetString("Button_ClearLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export CSV 的本地化字符串。
        /// </summary>
        public static string Button_ExportCsv {
            get {
                return ResourceManager.GetString("Button_ExportCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export JSON 的本地化字符串。
        /// </summary>
        public static string Button_ExportJson {
            get {
                return ResourceManager.GetString("Button_ExportJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Sessions 的本地化字符串。
        /// </summary>
        public static string Button_ExportSessions {
            get {
                return ResourceManager.GetString("Button_ExportSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller 的本地化字符串。
        /// </summary>
        public static string Button_NavigateController {
            get {
                return ResourceManager.GetString("Button_NavigateController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware 的本地化字符串。
        /// </summary>
        public static string Button_NavigateHardware {
            get {
                return ResourceManager.GetString("Button_NavigateHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module 的本地化字符串。
        /// </summary>
        public static string Button_NavigateModule {
            get {
                return ResourceManager.GetString("Button_NavigateModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor 的本地化字符串。
        /// </summary>
        public static string Button_NavigateMonitor {
            get {
                return ResourceManager.GetString("Button_NavigateMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow 的本地化字符串。
        /// </summary>
        public static string Button_NavigateWorkflow {
            get {
                return ResourceManager.GetString("Button_NavigateWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Button_Refresh {
            get {
                return ResourceManager.GetString("Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload 的本地化字符串。
        /// </summary>
        public static string Button_Reload {
            get {
                return ResourceManager.GetString("Button_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string Button_Remove {
            get {
                return ResourceManager.GetString("Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string Button_Reset {
            get {
                return ResourceManager.GetString("Button_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string Button_Start {
            get {
                return ResourceManager.GetString("Button_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string Button_Stop {
            get {
                return ResourceManager.GetString("Button_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Avg Duration 的本地化字符串。
        /// </summary>
        public static string CardTitle_AvgDuration {
            get {
                return ResourceManager.GetString("CardTitle_AvgDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancelled 的本地化字符串。
        /// </summary>
        public static string CardTitle_Cancelled {
            get {
                return ResourceManager.GetString("CardTitle_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controllers 的本地化字符串。
        /// </summary>
        public static string CardTitle_Controllers {
            get {
                return ResourceManager.GetString("CardTitle_Controllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        public static string CardTitle_Failed {
            get {
                return ResourceManager.GetString("CardTitle_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware 的本地化字符串。
        /// </summary>
        public static string CardTitle_Hardware {
            get {
                return ResourceManager.GetString("CardTitle_Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string CardTitle_Success {
            get {
                return ResourceManager.GetString("CardTitle_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success Rate 的本地化字符串。
        /// </summary>
        public static string CardTitle_SuccessRate {
            get {
                return ResourceManager.GetString("CardTitle_SuccessRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today 的本地化字符串。
        /// </summary>
        public static string CardTitle_Today {
            get {
                return ResourceManager.GetString("CardTitle_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Sessions 的本地化字符串。
        /// </summary>
        public static string CardTitle_TotalSessions {
            get {
                return ResourceManager.GetString("CardTitle_TotalSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflows 的本地化字符串。
        /// </summary>
        public static string CardTitle_Workflows {
            get {
                return ResourceManager.GetString("CardTitle_Workflows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Async 的本地化字符串。
        /// </summary>
        public static string CheckBox_Async {
            get {
                return ResourceManager.GetString("CheckBox_Async", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continue on Failure 的本地化字符串。
        /// </summary>
        public static string CheckBox_ContinueOnFailure {
            get {
                return ResourceManager.GetString("CheckBox_ContinueOnFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string CheckBox_Enabled {
            get {
                return ResourceManager.GetString("CheckBox_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reusable 的本地化字符串。
        /// </summary>
        public static string CheckBox_Reusable {
            get {
                return ResourceManager.GetString("CheckBox_Reusable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set as Default 的本地化字符串。
        /// </summary>
        public static string CheckBox_SetAsDefault {
            get {
                return ResourceManager.GetString("CheckBox_SetAsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected Controller Type * 的本地化字符串。
        /// </summary>
        public static string ComboBox_Controller {
            get {
                return ResourceManager.GetString("ComboBox_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Language 的本地化字符串。
        /// </summary>
        public static string ComboBox_SelectLanguage {
            get {
                return ResourceManager.GetString("ComboBox_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beckhoff 的本地化字符串。
        /// </summary>
        public static string ComboBoxItem_Beckhoff {
            get {
                return ResourceManager.GetString("ComboBoxItem_Beckhoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can 的本地化字符串。
        /// </summary>
        public static string ComboBoxItem_Can {
            get {
                return ResourceManager.GetString("ComboBoxItem_Can", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeadSys 的本地化字符串。
        /// </summary>
        public static string ComboBoxItem_LeadSys {
            get {
                return ResourceManager.GetString("ComboBoxItem_LeadSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parallel 的本地化字符串。
        /// </summary>
        public static string ComboBoxItem_Parallel {
            get {
                return ResourceManager.GetString("ComboBoxItem_Parallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plc 的本地化字符串。
        /// </summary>
        public static string ComboBoxItem_Plc {
            get {
                return ResourceManager.GetString("ComboBoxItem_Plc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequential 的本地化字符串。
        /// </summary>
        public static string ComboBoxItem_Sequential {
            get {
                return ResourceManager.GetString("ComboBoxItem_Sequential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Siemens 的本地化字符串。
        /// </summary>
        public static string ComboBoxItem_Siemens {
            get {
                return ResourceManager.GetString("ComboBoxItem_Siemens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ZLG 的本地化字符串。
        /// </summary>
        public static string ComboBoxItem_Zlg {
            get {
                return ResourceManager.GetString("ComboBoxItem_Zlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExecutedAt,LogType,FlowName,ModuleName,StepName,HardwareName,CommandName,IsSuccess,DurationMs,ErrorMessage,IsCancelled 的本地化字符串。
        /// </summary>
        public static string CsvHeader_ExecutionLogs {
            get {
                return ResourceManager.GetString("CsvHeader_ExecutionLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name,StartedAt,CompletedAt,IsSuccess,TotalDurationMs,FlowCount,ModuleCount,StepCount,SuccessStepCount,FailedStepCount,IsCancelled,CancelReason 的本地化字符串。
        /// </summary>
        public static string CsvHeader_ExecutionSessions {
            get {
                return ResourceManager.GetString("CsvHeader_ExecutionSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hardware_workflow.db 的本地化字符串。
        /// </summary>
        public static string Default_DatabasePath {
            get {
                return ResourceManager.GetString("Default_DatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DLL Files (*.dll)|*.dll|All Files (*.*)|*.* 的本地化字符串。
        /// </summary>
        public static string DialogFilter_DllFiles {
            get {
                return ResourceManager.GetString("DialogFilter_DllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQLite Database (*.db)|*.db|All Files (*.*)|*.* 的本地化字符串。
        /// </summary>
        public static string DialogFilter_SqliteDatabase {
            get {
                return ResourceManager.GetString("DialogFilter_SqliteDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select CAN DLL 的本地化字符串。
        /// </summary>
        public static string DialogTitle_SelectCanDll {
            get {
                return ResourceManager.GetString("DialogTitle_SelectCanDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select PLC DLL 的本地化字符串。
        /// </summary>
        public static string DialogTitle_SelectPlcDll {
            get {
                return ResourceManager.GetString("DialogTitle_SelectPlcDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string FilterOption_All {
            get {
                return ResourceManager.GetString("FilterOption_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller 的本地化字符串。
        /// </summary>
        public static string FilterOption_Controller {
            get {
                return ResourceManager.GetString("FilterOption_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        public static string FilterOption_Failed {
            get {
                return ResourceManager.GetString("FilterOption_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flow 的本地化字符串。
        /// </summary>
        public static string FilterOption_Flow {
            get {
                return ResourceManager.GetString("FilterOption_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module 的本地化字符串。
        /// </summary>
        public static string FilterOption_Module {
            get {
                return ResourceManager.GetString("FilterOption_Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step 的本地化字符串。
        /// </summary>
        public static string FilterOption_Step {
            get {
                return ResourceManager.GetString("FilterOption_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string FilterOption_Success {
            get {
                return ResourceManager.GetString("FilterOption_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CAN: {0} 的本地化字符串。
        /// </summary>
        public static string Format_CanCount {
            get {
                return ResourceManager.GetString("Format_CanCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cool: {0} 的本地化字符串。
        /// </summary>
        public static string Format_CoolingCount {
            get {
                return ResourceManager.GetString("Format_CoolingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom: {0} 的本地化字符串。
        /// </summary>
        public static string Format_CustomCount {
            get {
                return ResourceManager.GetString("Format_CustomCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed: {0} 的本地化字符串。
        /// </summary>
        public static string Format_FailedCount {
            get {
                return ResourceManager.GetString("Format_FailedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flow #{0} 的本地化字符串。
        /// </summary>
        public static string Format_FlowReference {
            get {
                return ResourceManager.GetString("Format_FlowReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Retention (days): {0} 的本地化字符串。
        /// </summary>
        public static string Format_LogRetentionDays {
            get {
                return ResourceManager.GetString("Format_LogRetentionDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Concurrent Slots: {0} 的本地化字符串。
        /// </summary>
        public static string Format_MaxConcurrentSlots {
            get {
                return ResourceManager.GetString("Format_MaxConcurrentSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} ({1} - {2} steps) 的本地化字符串。
        /// </summary>
        public static string Format_ModuleItem {
            get {
                return ResourceManager.GetString("Format_ModuleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module #{0} 的本地化字符串。
        /// </summary>
        public static string Format_ModuleReference {
            get {
                return ResourceManager.GetString("Format_ModuleReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Motor: {0} 的本地化字符串。
        /// </summary>
        public static string Format_MotorCount {
            get {
                return ResourceManager.GetString("Format_MotorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name: {0} 的本地化字符串。
        /// </summary>
        public static string Format_NameLabel {
            get {
                return ResourceManager.GetString("Format_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} ({1}) 的本地化字符串。
        /// </summary>
        public static string Format_NameWithDetail {
            get {
                return ResourceManager.GetString("Format_NameWithDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLC: {0} 的本地化字符串。
        /// </summary>
        public static string Format_PlcCount {
            get {
                return ResourceManager.GetString("Format_PlcCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reusable: {0} 的本地化字符串。
        /// </summary>
        public static string Format_ReusableCount {
            get {
                return ResourceManager.GetString("Format_ReusableCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step {0} 的本地化字符串。
        /// </summary>
        public static string Format_StepName {
            get {
                return ResourceManager.GetString("Format_StepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step &apos;{0}&apos;: {1} 的本地化字符串。
        /// </summary>
        public static string Format_StepValidationError {
            get {
                return ResourceManager.GetString("Format_StepValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success: {0} 的本地化字符串。
        /// </summary>
        public static string Format_SuccessCount {
            get {
                return ResourceManager.GetString("Format_SuccessCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Temp: {0} 的本地化字符串。
        /// </summary>
        public static string Format_TemperatureCount {
            get {
                return ResourceManager.GetString("Format_TemperatureCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type: {0} 的本地化字符串。
        /// </summary>
        public static string Format_TypeLabel {
            get {
                return ResourceManager.GetString("Format_TypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Actions 的本地化字符串。
        /// </summary>
        public static string Header_Actions {
            get {
                return ResourceManager.GetString("Header_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        public static string Header_Address {
            get {
                return ResourceManager.GetString("Header_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alias 的本地化字符串。
        /// </summary>
        public static string Header_Alias {
            get {
                return ResourceManager.GetString("Header_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Category 的本地化字符串。
        /// </summary>
        public static string Header_Category {
            get {
                return ResourceManager.GetString("Header_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command 的本地化字符串。
        /// </summary>
        public static string Header_Command {
            get {
                return ResourceManager.GetString("Header_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ContinueOnFail 的本地化字符串。
        /// </summary>
        public static string Header_ContinueOnFail {
            get {
                return ResourceManager.GetString("Header_ContinueOnFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller 的本地化字符串。
        /// </summary>
        public static string Header_Controller {
            get {
                return ResourceManager.GetString("Header_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control Profile 的本地化字符串。
        /// </summary>
        public static string Header_ControlProfile {
            get {
                return ResourceManager.GetString("Header_ControlProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string Header_Default {
            get {
                return ResourceManager.GetString("Header_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string Header_Description {
            get {
                return ResourceManager.GetString("Header_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duration 的本地化字符串。
        /// </summary>
        public static string Header_Duration {
            get {
                return ResourceManager.GetString("Header_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duration (ms) 的本地化字符串。
        /// </summary>
        public static string Header_DurationMs {
            get {
                return ResourceManager.GetString("Header_DurationMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string Header_Enabled {
            get {
                return ResourceManager.GetString("Header_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Header_Error {
            get {
                return ResourceManager.GetString("Header_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flow 的本地化字符串。
        /// </summary>
        public static string Header_Flow {
            get {
                return ResourceManager.GetString("Header_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flows 的本地化字符串。
        /// </summary>
        public static string Header_Flows {
            get {
                return ResourceManager.GetString("Header_Flows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware 的本地化字符串。
        /// </summary>
        public static string Header_Hardware {
            get {
                return ResourceManager.GetString("Header_Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mode 的本地化字符串。
        /// </summary>
        public static string Header_Mode {
            get {
                return ResourceManager.GetString("Header_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module 的本地化字符串。
        /// </summary>
        public static string Header_Module {
            get {
                return ResourceManager.GetString("Header_Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Header_Name {
            get {
                return ResourceManager.GetString("Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nodes 的本地化字符串。
        /// </summary>
        public static string Header_Nodes {
            get {
                return ResourceManager.GetString("Header_Nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note 的本地化字符串。
        /// </summary>
        public static string Header_Note {
            get {
                return ResourceManager.GetString("Header_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 # 的本地化字符串。
        /// </summary>
        public static string Header_Number {
            get {
                return ResourceManager.GetString("Header_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string Header_Ok {
            get {
                return ResourceManager.GetString("Header_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        public static string Header_Port {
            get {
                return ResourceManager.GetString("Header_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reusable 的本地化字符串。
        /// </summary>
        public static string Header_Reusable {
            get {
                return ResourceManager.GetString("Header_Reusable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Started 的本地化字符串。
        /// </summary>
        public static string Header_Started {
            get {
                return ResourceManager.GetString("Header_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State 的本地化字符串。
        /// </summary>
        public static string Header_State {
            get {
                return ResourceManager.GetString("Header_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step 的本地化字符串。
        /// </summary>
        public static string Header_Step {
            get {
                return ResourceManager.GetString("Header_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steps 的本地化字符串。
        /// </summary>
        public static string Header_Steps {
            get {
                return ResourceManager.GetString("Header_Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string Header_Success {
            get {
                return ResourceManager.GetString("Header_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        public static string Header_System {
            get {
                return ResourceManager.GetString("Header_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tags 的本地化字符串。
        /// </summary>
        public static string Header_Tags {
            get {
                return ResourceManager.GetString("Header_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        public static string Header_Time {
            get {
                return ResourceManager.GetString("Header_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string Header_Type {
            get {
                return ResourceManager.GetString("Header_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vendor 的本地化字符串。
        /// </summary>
        public static string Header_Vendor {
            get {
                return ResourceManager.GetString("Header_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        public static string Hint_Address {
            get {
                return ResourceManager.GetString("Hint_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alias 的本地化字符串。
        /// </summary>
        public static string Hint_Alias {
            get {
                return ResourceManager.GetString("Hint_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CAN DLL path (e.g., zlgcan.dll) 的本地化字符串。
        /// </summary>
        public static string Hint_CanDllPath {
            get {
                return ResourceManager.GetString("Hint_CanDllPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command Parameters JSON 的本地化字符串。
        /// </summary>
        public static string Hint_CommandParametersJson {
            get {
                return ResourceManager.GetString("Hint_CommandParametersJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command * 的本地化字符串。
        /// </summary>
        public static string Hint_CommandRequired {
            get {
                return ResourceManager.GetString("Hint_CommandRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Condition 的本地化字符串。
        /// </summary>
        public static string Hint_Condition {
            get {
                return ResourceManager.GetString("Hint_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection Config JSON * 的本地化字符串。
        /// </summary>
        public static string Hint_ConnectionConfigJsonRequired {
            get {
                return ResourceManager.GetString("Hint_ConnectionConfigJsonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller Type * 的本地化字符串。
        /// </summary>
        public static string Hint_ControllerTypeRequired {
            get {
                return ResourceManager.GetString("Hint_ControllerTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control Profile * 的本地化字符串。
        /// </summary>
        public static string Hint_ControlProfileRequired {
            get {
                return ResourceManager.GetString("Hint_ControlProfileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Schema JSON 的本地化字符串。
        /// </summary>
        public static string Hint_CustomSchemaJson {
            get {
                return ResourceManager.GetString("Hint_CustomSchemaJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Execution Mode 的本地化字符串。
        /// </summary>
        public static string Hint_DefaultExecutionMode {
            get {
                return ResourceManager.GetString("Hint_DefaultExecutionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Parameters JSON 的本地化字符串。
        /// </summary>
        public static string Hint_DefaultParametersJson {
            get {
                return ResourceManager.GetString("Hint_DefaultParametersJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string Hint_Description {
            get {
                return ResourceManager.GetString("Hint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execution Mode 的本地化字符串。
        /// </summary>
        public static string Hint_ExecutionMode {
            get {
                return ResourceManager.GetString("Hint_ExecutionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware Category * 的本地化字符串。
        /// </summary>
        public static string Hint_HardwareCategoryRequired {
            get {
                return ResourceManager.GetString("Hint_HardwareCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware Definition * 的本地化字符串。
        /// </summary>
        public static string Hint_HardwareDefinitionRequired {
            get {
                return ResourceManager.GetString("Hint_HardwareDefinitionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware Instance * 的本地化字符串。
        /// </summary>
        public static string Hint_HardwareInstanceRequired {
            get {
                return ResourceManager.GetString("Hint_HardwareInstanceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module Name * 的本地化字符串。
        /// </summary>
        public static string Hint_ModuleNameRequired {
            get {
                return ResourceManager.GetString("Hint_ModuleNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name * 的本地化字符串。
        /// </summary>
        public static string Hint_NameRequired {
            get {
                return ResourceManager.GetString("Hint_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note 的本地化字符串。
        /// </summary>
        public static string Hint_Note {
            get {
                return ResourceManager.GetString("Hint_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameters JSON 的本地化字符串。
        /// </summary>
        public static string Hint_ParametersJson {
            get {
                return ResourceManager.GetString("Hint_ParametersJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLC DLL path (e.g., EPAN.dll) 的本地化字符串。
        /// </summary>
        public static string Hint_PlcDllPath {
            get {
                return ResourceManager.GetString("Hint_PlcDllPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port / Channel 的本地化字符串。
        /// </summary>
        public static string Hint_PortChannel {
            get {
                return ResourceManager.GetString("Hint_PortChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search controllers... 的本地化字符串。
        /// </summary>
        public static string Hint_SearchControllers {
            get {
                return ResourceManager.GetString("Hint_SearchControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search hardware... 的本地化字符串。
        /// </summary>
        public static string Hint_SearchHardware {
            get {
                return ResourceManager.GetString("Hint_SearchHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search hardware definitions... 的本地化字符串。
        /// </summary>
        public static string Hint_SearchHardwareDefinitions {
            get {
                return ResourceManager.GetString("Hint_SearchHardwareDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search modules... 的本地化字符串。
        /// </summary>
        public static string Hint_SearchModules {
            get {
                return ResourceManager.GetString("Hint_SearchModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search workflows... 的本地化字符串。
        /// </summary>
        public static string Hint_SearchWorkflows {
            get {
                return ResourceManager.GetString("Hint_SearchWorkflows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Module to Add 的本地化字符串。
        /// </summary>
        public static string Hint_SelectModuleToAdd {
            get {
                return ResourceManager.GetString("Hint_SelectModuleToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Sub-Flow to Add 的本地化字符串。
        /// </summary>
        public static string Hint_SelectSubFlowToAdd {
            get {
                return ResourceManager.GetString("Hint_SelectSubFlowToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQLite database file path 的本地化字符串。
        /// </summary>
        public static string Hint_SqliteDatabasePath {
            get {
                return ResourceManager.GetString("Hint_SqliteDatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step Name * 的本地化字符串。
        /// </summary>
        public static string Hint_StepNameRequired {
            get {
                return ResourceManager.GetString("Hint_StepNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step Timeout (ms) 的本地化字符串。
        /// </summary>
        public static string Hint_StepTimeoutMs {
            get {
                return ResourceManager.GetString("Hint_StepTimeoutMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tags (comma separated) 的本地化字符串。
        /// </summary>
        public static string Hint_TagsCommaSeparated {
            get {
                return ResourceManager.GetString("Hint_TagsCommaSeparated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout (ms) 的本地化字符串。
        /// </summary>
        public static string Hint_TimeoutMs {
            get {
                return ResourceManager.GetString("Hint_TimeoutMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vendor Name * 的本地化字符串。
        /// </summary>
        public static string Hint_VendorNameRequired {
            get {
                return ResourceManager.GetString("Hint_VendorNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow Name * 的本地化字符串。
        /// </summary>
        public static string Hint_WorkflowNameRequired {
            get {
                return ResourceManager.GetString("Hint_WorkflowNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Theme 的本地化字符串。
        /// </summary>
        public static string Label_DarkTheme {
            get {
                return ResourceManager.GetString("Label_DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From 的本地化字符串。
        /// </summary>
        public static string Label_From {
            get {
                return ResourceManager.GetString("Label_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Type: 的本地化字符串。
        /// </summary>
        public static string Label_LogType {
            get {
                return ResourceManager.GetString("Label_LogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module 的本地化字符串。
        /// </summary>
        public static string Label_Module {
            get {
                return ResourceManager.GetString("Label_Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Navigation 的本地化字符串。
        /// </summary>
        public static string Label_Navigation {
            get {
                return ResourceManager.GetString("Label_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Label_Search {
            get {
                return ResourceManager.GetString("Label_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SubFlow 的本地化字符串。
        /// </summary>
        public static string Label_SubFlow {
            get {
                return ResourceManager.GetString("Label_SubFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To 的本地化字符串。
        /// </summary>
        public static string Label_To {
            get {
                return ResourceManager.GetString("Label_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        public static string Label_Unknown {
            get {
                return ResourceManager.GetString("Label_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsaved 的本地化字符串。
        /// </summary>
        public static string Label_Unsaved {
            get {
                return ResourceManager.GetString("Label_Unsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 en-US 的本地化字符串。
        /// </summary>
        public static string Language_EnUs {
            get {
                return ResourceManager.GetString("Language_EnUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-CN 的本地化字符串。
        /// </summary>
        public static string Language_ZhCn {
            get {
                return ResourceManager.GetString("Language_ZhCn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adding hardware definition... 的本地化字符串。
        /// </summary>
        public static string Message_AddingHardwareDefinition {
            get {
                return ResourceManager.GetString("Message_AddingHardwareDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adding new controller... 的本地化字符串。
        /// </summary>
        public static string Message_AddingNewController {
            get {
                return ResourceManager.GetString("Message_AddingNewController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adding new hardware... 的本地化字符串。
        /// </summary>
        public static string Message_AddingNewHardware {
            get {
                return ResourceManager.GetString("Message_AddingNewHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adding new module... 的本地化字符串。
        /// </summary>
        public static string Message_AddingNewModule {
            get {
                return ResourceManager.GetString("Message_AddingNewModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adding new workflow... 的本地化字符串。
        /// </summary>
        public static string Message_AddingNewWorkflow {
            get {
                return ResourceManager.GetString("Message_AddingNewWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All executions cancelled 的本地化字符串。
        /// </summary>
        public static string Message_AllExecutionsCancelled {
            get {
                return ResourceManager.GetString("Message_AllExecutionsCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot reference the workflow itself 的本地化字符串。
        /// </summary>
        public static string Message_CannotReferenceWorkflowItself {
            get {
                return ResourceManager.GetString("Message_CannotReferenceWorkflowItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller &apos;{0}&apos; created 的本地化字符串。
        /// </summary>
        public static string Message_ControllerCreated {
            get {
                return ResourceManager.GetString("Message_ControllerCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller &apos;{0}&apos; deleted 的本地化字符串。
        /// </summary>
        public static string Message_ControllerDeleted {
            get {
                return ResourceManager.GetString("Message_ControllerDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected controller is not compatible with this definition 的本地化字符串。
        /// </summary>
        public static string Message_ControllerNotCompatible {
            get {
                return ResourceManager.GetString("Message_ControllerNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller &apos;{0}&apos; updated 的本地化字符串。
        /// </summary>
        public static string Message_ControllerUpdated {
            get {
                return ResourceManager.GetString("Message_ControllerUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dashboard refreshed at {0} 的本地化字符串。
        /// </summary>
        public static string Message_DashboardRefreshedAt {
            get {
                return ResourceManager.GetString("Message_DashboardRefreshedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit cancelled 的本地化字符串。
        /// </summary>
        public static string Message_EditCancelled {
            get {
                return ResourceManager.GetString("Message_EditCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Editing {0}... 的本地化字符串。
        /// </summary>
        public static string Message_EditingName {
            get {
                return ResourceManager.GetString("Message_EditingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exported to {0} 的本地化字符串。
        /// </summary>
        public static string Message_ExportedToPath {
            get {
                return ResourceManager.GetString("Message_ExportedToPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export failed: {0} 的本地化字符串。
        /// </summary>
        public static string Message_ExportFailed {
            get {
                return ResourceManager.GetString("Message_ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to cancel: {0} 的本地化字符串。
        /// </summary>
        public static string Message_FailedToCancel {
            get {
                return ResourceManager.GetString("Message_FailedToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to delete: {0} 的本地化字符串。
        /// </summary>
        public static string Message_FailedToDelete {
            get {
                return ResourceManager.GetString("Message_FailedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load: {0} 的本地化字符串。
        /// </summary>
        public static string Message_FailedToLoad {
            get {
                return ResourceManager.GetString("Message_FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load logs: {0} 的本地化字符串。
        /// </summary>
        public static string Message_FailedToLoadLogs {
            get {
                return ResourceManager.GetString("Message_FailedToLoadLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load settings: {0} 的本地化字符串。
        /// </summary>
        public static string Message_FailedToLoadSettings {
            get {
                return ResourceManager.GetString("Message_FailedToLoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to refresh: {0} 的本地化字符串。
        /// </summary>
        public static string Message_FailedToRefresh {
            get {
                return ResourceManager.GetString("Message_FailedToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to refresh: {0} 的本地化字符串。
        /// </summary>
        public static string Message_FailedToRefreshDashboard {
            get {
                return ResourceManager.GetString("Message_FailedToRefreshDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save: {0} 的本地化字符串。
        /// </summary>
        public static string Message_FailedToSave {
            get {
                return ResourceManager.GetString("Message_FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save settings: {0} 的本地化字符串。
        /// </summary>
        public static string Message_FailedToSaveSettings {
            get {
                return ResourceManager.GetString("Message_FailedToSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to start runtime: {0} 的本地化字符串。
        /// </summary>
        public static string Message_FailedToStartRuntime {
            get {
                return ResourceManager.GetString("Message_FailedToStartRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to stop runtime: {0} 的本地化字符串。
        /// </summary>
        public static string Message_FailedToStopRuntime {
            get {
                return ResourceManager.GetString("Message_FailedToStopRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected hardware category is unavailable 的本地化字符串。
        /// </summary>
        public static string Message_HardwareCategoryUnavailable {
            get {
                return ResourceManager.GetString("Message_HardwareCategoryUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware &apos;{0}&apos; created 的本地化字符串。
        /// </summary>
        public static string Message_HardwareCreated {
            get {
                return ResourceManager.GetString("Message_HardwareCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware definition &apos;{0}&apos; created 的本地化字符串。
        /// </summary>
        public static string Message_HardwareDefinitionCreated {
            get {
                return ResourceManager.GetString("Message_HardwareDefinitionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware definition &apos;{0}&apos; deleted 的本地化字符串。
        /// </summary>
        public static string Message_HardwareDefinitionDeleted {
            get {
                return ResourceManager.GetString("Message_HardwareDefinitionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected hardware definition is unavailable 的本地化字符串。
        /// </summary>
        public static string Message_HardwareDefinitionUnavailable {
            get {
                return ResourceManager.GetString("Message_HardwareDefinitionUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware definition &apos;{0}&apos; updated 的本地化字符串。
        /// </summary>
        public static string Message_HardwareDefinitionUpdated {
            get {
                return ResourceManager.GetString("Message_HardwareDefinitionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware &apos;{0}&apos; deleted 的本地化字符串。
        /// </summary>
        public static string Message_HardwareDeleted {
            get {
                return ResourceManager.GetString("Message_HardwareDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected hardware profile does not support the previous command 的本地化字符串。
        /// </summary>
        public static string Message_HardwareProfileDoesNotSupportCommand {
            get {
                return ResourceManager.GetString("Message_HardwareProfileDoesNotSupportCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware refreshed 的本地化字符串。
        /// </summary>
        public static string Message_HardwareRefreshed {
            get {
                return ResourceManager.GetString("Message_HardwareRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware &apos;{0}&apos; updated 的本地化字符串。
        /// </summary>
        public static string Message_HardwareUpdated {
            get {
                return ResourceManager.GetString("Message_HardwareUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid JSON in {0} 的本地化字符串。
        /// </summary>
        public static string Message_InvalidJsonInField {
            get {
                return ResourceManager.GetString("Message_InvalidJsonInField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Live logs cleared 的本地化字符串。
        /// </summary>
        public static string Message_LiveLogsCleared {
            get {
                return ResourceManager.GetString("Message_LiveLogsCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded {0} controllers 的本地化字符串。
        /// </summary>
        public static string Message_LoadedControllers {
            get {
                return ResourceManager.GetString("Message_LoadedControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded {0} hardware definitions 的本地化字符串。
        /// </summary>
        public static string Message_LoadedHardwareDefinitions {
            get {
                return ResourceManager.GetString("Message_LoadedHardwareDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded {0} hardware instances 的本地化字符串。
        /// </summary>
        public static string Message_LoadedHardwareInstances {
            get {
                return ResourceManager.GetString("Message_LoadedHardwareInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded {0} logs for session &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        public static string Message_LoadedLogsForSession {
            get {
                return ResourceManager.GetString("Message_LoadedLogsForSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded {0} modules 的本地化字符串。
        /// </summary>
        public static string Message_LoadedModules {
            get {
                return ResourceManager.GetString("Message_LoadedModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded {0} sessions 的本地化字符串。
        /// </summary>
        public static string Message_LoadedSessions {
            get {
                return ResourceManager.GetString("Message_LoadedSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded {0} workflows 的本地化字符串。
        /// </summary>
        public static string Message_LoadedWorkflows {
            get {
                return ResourceManager.GetString("Message_LoadedWorkflows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading controllers... 的本地化字符串。
        /// </summary>
        public static string Message_LoadingControllers {
            get {
                return ResourceManager.GetString("Message_LoadingControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading execution logs... 的本地化字符串。
        /// </summary>
        public static string Message_LoadingExecutionLogs {
            get {
                return ResourceManager.GetString("Message_LoadingExecutionLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading hardware... 的本地化字符串。
        /// </summary>
        public static string Message_LoadingHardware {
            get {
                return ResourceManager.GetString("Message_LoadingHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading hardware definitions... 的本地化字符串。
        /// </summary>
        public static string Message_LoadingHardwareDefinitions {
            get {
                return ResourceManager.GetString("Message_LoadingHardwareDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading modules... 的本地化字符串。
        /// </summary>
        public static string Message_LoadingModules {
            get {
                return ResourceManager.GetString("Message_LoadingModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading workflows... 的本地化字符串。
        /// </summary>
        public static string Message_LoadingWorkflows {
            get {
                return ResourceManager.GetString("Message_LoadingWorkflows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module &apos;{0}&apos; added to workflow 的本地化字符串。
        /// </summary>
        public static string Message_ModuleAddedToWorkflow {
            get {
                return ResourceManager.GetString("Message_ModuleAddedToWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module &apos;{0}&apos; created with {1} steps 的本地化字符串。
        /// </summary>
        public static string Message_ModuleCreatedWithSteps {
            get {
                return ResourceManager.GetString("Message_ModuleCreatedWithSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module &apos;{0}&apos; deleted 的本地化字符串。
        /// </summary>
        public static string Message_ModuleDeleted {
            get {
                return ResourceManager.GetString("Message_ModuleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module &apos;{0}&apos; updated with {1} steps 的本地化字符串。
        /// </summary>
        public static string Message_ModuleUpdatedWithSteps {
            get {
                return ResourceManager.GetString("Message_ModuleUpdatedWithSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor refreshed: {0} hardware, {1} sessions 的本地化字符串。
        /// </summary>
        public static string Message_MonitorRefreshed {
            get {
                return ResourceManager.GetString("Message_MonitorRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Node removed 的本地化字符串。
        /// </summary>
        public static string Message_NodeRemoved {
            get {
                return ResourceManager.GetString("Message_NodeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No logs to export 的本地化字符串。
        /// </summary>
        public static string Message_NoLogsToExport {
            get {
                return ResourceManager.GetString("Message_NoLogsToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No sessions to export 的本地化字符串。
        /// </summary>
        public static string Message_NoSessionsToExport {
            get {
                return ResourceManager.GetString("Message_NoSessionsToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refreshing dashboard... 的本地化字符串。
        /// </summary>
        public static string Message_RefreshingDashboard {
            get {
                return ResourceManager.GetString("Message_RefreshingDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refreshing monitor data... 的本地化字符串。
        /// </summary>
        public static string Message_RefreshingMonitorData {
            get {
                return ResourceManager.GetString("Message_RefreshingMonitorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Runtime started 的本地化字符串。
        /// </summary>
        public static string Message_RuntimeStarted {
            get {
                return ResourceManager.GetString("Message_RuntimeStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Runtime stopped 的本地化字符串。
        /// </summary>
        public static string Message_RuntimeStopped {
            get {
                return ResourceManager.GetString("Message_RuntimeStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings loaded 的本地化字符串。
        /// </summary>
        public static string Message_SettingsLoaded {
            get {
                return ResourceManager.GetString("Message_SettingsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings reset to defaults 的本地化字符串。
        /// </summary>
        public static string Message_SettingsResetToDefaults {
            get {
                return ResourceManager.GetString("Message_SettingsResetToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings saved successfully 的本地化字符串。
        /// </summary>
        public static string Message_SettingsSavedSuccessfully {
            get {
                return ResourceManager.GetString("Message_SettingsSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step added 的本地化字符串。
        /// </summary>
        public static string Message_StepAdded {
            get {
                return ResourceManager.GetString("Message_StepAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step removed 的本地化字符串。
        /// </summary>
        public static string Message_StepRemoved {
            get {
                return ResourceManager.GetString("Message_StepRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sub-flow &apos;{0}&apos; added to workflow 的本地化字符串。
        /// </summary>
        public static string Message_SubFlowAddedToWorkflow {
            get {
                return ResourceManager.GetString("Message_SubFlowAddedToWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Testing connection to &apos;{0}&apos;... 的本地化字符串。
        /// </summary>
        public static string Message_TestingConnectionPlaceholder {
            get {
                return ResourceManager.GetString("Message_TestingConnectionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow &apos;{0}&apos; created with {1} nodes 的本地化字符串。
        /// </summary>
        public static string Message_WorkflowCreatedWithNodes {
            get {
                return ResourceManager.GetString("Message_WorkflowCreatedWithNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow &apos;{0}&apos; deleted 的本地化字符串。
        /// </summary>
        public static string Message_WorkflowDeleted {
            get {
                return ResourceManager.GetString("Message_WorkflowDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow &apos;{0}&apos; updated with {1} nodes 的本地化字符串。
        /// </summary>
        public static string Message_WorkflowUpdatedWithNodes {
            get {
                return ResourceManager.GetString("Message_WorkflowUpdatedWithNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller 的本地化字符串。
        /// </summary>
        public static string Navigation_Controller {
            get {
                return ResourceManager.GetString("Navigation_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dashboard 的本地化字符串。
        /// </summary>
        public static string Navigation_Dashboard {
            get {
                return ResourceManager.GetString("Navigation_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execution Log 的本地化字符串。
        /// </summary>
        public static string Navigation_ExecutionLog {
            get {
                return ResourceManager.GetString("Navigation_ExecutionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware 的本地化字符串。
        /// </summary>
        public static string Navigation_Hardware {
            get {
                return ResourceManager.GetString("Navigation_Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware Definitions 的本地化字符串。
        /// </summary>
        public static string Navigation_HardwareDefinitions {
            get {
                return ResourceManager.GetString("Navigation_HardwareDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module 的本地化字符串。
        /// </summary>
        public static string Navigation_Module {
            get {
                return ResourceManager.GetString("Navigation_Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor 的本地化字符串。
        /// </summary>
        public static string Navigation_Monitor {
            get {
                return ResourceManager.GetString("Navigation_Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Navigation_Settings {
            get {
                return ResourceManager.GetString("Navigation_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow 的本地化字符串。
        /// </summary>
        public static string Navigation_Workflow {
            get {
                return ResourceManager.GetString("Navigation_Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller Management 的本地化字符串。
        /// </summary>
        public static string PageTitle_ControllerManagement {
            get {
                return ResourceManager.GetString("PageTitle_ControllerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dashboard 的本地化字符串。
        /// </summary>
        public static string PageTitle_Dashboard {
            get {
                return ResourceManager.GetString("PageTitle_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execution Log 的本地化字符串。
        /// </summary>
        public static string PageTitle_ExecutionLog {
            get {
                return ResourceManager.GetString("PageTitle_ExecutionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execution Monitor 的本地化字符串。
        /// </summary>
        public static string PageTitle_ExecutionMonitor {
            get {
                return ResourceManager.GetString("PageTitle_ExecutionMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware Definitions 的本地化字符串。
        /// </summary>
        public static string PageTitle_HardwareDefinitions {
            get {
                return ResourceManager.GetString("PageTitle_HardwareDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware Management 的本地化字符串。
        /// </summary>
        public static string PageTitle_HardwareManagement {
            get {
                return ResourceManager.GetString("PageTitle_HardwareManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module Editor 的本地化字符串。
        /// </summary>
        public static string PageTitle_ModuleEditor {
            get {
                return ResourceManager.GetString("PageTitle_ModuleEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string PageTitle_Settings {
            get {
                return ResourceManager.GetString("PageTitle_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow Editor 的本地化字符串。
        /// </summary>
        public static string PageTitle_WorkflowEditor {
            get {
                return ResourceManager.GetString("PageTitle_WorkflowEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string Section_About {
            get {
                return ResourceManager.GetString("Section_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database 的本地化字符串。
        /// </summary>
        public static string Section_Database {
            get {
                return ResourceManager.GetString("Section_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DLL Paths 的本地化字符串。
        /// </summary>
        public static string Section_DllPaths {
            get {
                return ResourceManager.GetString("Section_DllPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Selected Node 的本地化字符串。
        /// </summary>
        public static string Section_EditSelectedNode {
            get {
                return ResourceManager.GetString("Section_EditSelectedNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Selected Step 的本地化字符串。
        /// </summary>
        public static string Section_EditSelectedStep {
            get {
                return ResourceManager.GetString("Section_EditSelectedStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execution Sessions 的本地化字符串。
        /// </summary>
        public static string Section_ExecutionSessions {
            get {
                return ResourceManager.GetString("Section_ExecutionSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter 的本地化字符串。
        /// </summary>
        public static string Section_Filter {
            get {
                return ResourceManager.GetString("Section_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flow Nodes 的本地化字符串。
        /// </summary>
        public static string Section_FlowNodes {
            get {
                return ResourceManager.GetString("Section_FlowNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string Section_General {
            get {
                return ResourceManager.GetString("Section_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware Status 的本地化字符串。
        /// </summary>
        public static string Section_HardwareStatus {
            get {
                return ResourceManager.GetString("Section_HardwareStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Live Event Log 的本地化字符串。
        /// </summary>
        public static string Section_LiveEventLog {
            get {
                return ResourceManager.GetString("Section_LiveEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logs 的本地化字符串。
        /// </summary>
        public static string Section_Logs {
            get {
                return ResourceManager.GetString("Section_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick Access 的本地化字符串。
        /// </summary>
        public static string Section_QuickAccess {
            get {
                return ResourceManager.GetString("Section_QuickAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent Events 的本地化字符串。
        /// </summary>
        public static string Section_RecentEvents {
            get {
                return ResourceManager.GetString("Section_RecentEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent Sessions 的本地化字符串。
        /// </summary>
        public static string Section_RecentSessions {
            get {
                return ResourceManager.GetString("Section_RecentSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scheduler 的本地化字符串。
        /// </summary>
        public static string Section_Scheduler {
            get {
                return ResourceManager.GetString("Section_Scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Session Log Details 的本地化字符串。
        /// </summary>
        public static string Section_SessionLogDetails {
            get {
                return ResourceManager.GetString("Section_SessionLogDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Session Logs 的本地化字符串。
        /// </summary>
        public static string Section_SessionLogs {
            get {
                return ResourceManager.GetString("Section_SessionLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steps 的本地化字符串。
        /// </summary>
        public static string Section_Steps {
            get {
                return ResourceManager.GetString("Section_Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No hardware connected 的本地化字符串。
        /// </summary>
        public static string Status_NoHardwareConnected {
            get {
                return ResourceManager.GetString("Status_NoHardwareConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        public static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Runtime is running 的本地化字符串。
        /// </summary>
        public static string Status_RuntimeRunning {
            get {
                return ResourceManager.GetString("Status_RuntimeRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Runtime is stopped 的本地化字符串。
        /// </summary>
        public static string Status_RuntimeStopped {
            get {
                return ResourceManager.GetString("Status_RuntimeStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Controller 的本地化字符串。
        /// </summary>
        public static string Title_AddController {
            get {
                return ResourceManager.GetString("Title_AddController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Hardware 的本地化字符串。
        /// </summary>
        public static string Title_AddHardware {
            get {
                return ResourceManager.GetString("Title_AddHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Hardware Definition 的本地化字符串。
        /// </summary>
        public static string Title_AddHardwareDefinition {
            get {
                return ResourceManager.GetString("Title_AddHardwareDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Module 的本地化字符串。
        /// </summary>
        public static string Title_AddModule {
            get {
                return ResourceManager.GetString("Title_AddModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Workflow 的本地化字符串。
        /// </summary>
        public static string Title_AddWorkflow {
            get {
                return ResourceManager.GetString("Title_AddWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Controller (ID: {0}) 的本地化字符串。
        /// </summary>
        public static string Title_EditController {
            get {
                return ResourceManager.GetString("Title_EditController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Hardware (ID: {0}) 的本地化字符串。
        /// </summary>
        public static string Title_EditHardware {
            get {
                return ResourceManager.GetString("Title_EditHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Hardware Definition (ID: {0}) 的本地化字符串。
        /// </summary>
        public static string Title_EditHardwareDefinition {
            get {
                return ResourceManager.GetString("Title_EditHardwareDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Module (ID: {0}) 的本地化字符串。
        /// </summary>
        public static string Title_EditModule {
            get {
                return ResourceManager.GetString("Title_EditModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Workflow (ID: {0}) 的本地化字符串。
        /// </summary>
        public static string Title_EditWorkflow {
            get {
                return ResourceManager.GetString("Title_EditWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware Modular Workflow 的本地化字符串。
        /// </summary>
        public static string Title_HardwareModularWorkflow {
            get {
                return ResourceManager.GetString("Title_HardwareModularWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel All 的本地化字符串。
        /// </summary>
        public static string Tooltip_CancelAll {
            get {
                return ResourceManager.GetString("Tooltip_CancelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Filters 的本地化字符串。
        /// </summary>
        public static string Tooltip_ClearFilters {
            get {
                return ResourceManager.GetString("Tooltip_ClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Live Logs 的本地化字符串。
        /// </summary>
        public static string Tooltip_ClearLiveLogs {
            get {
                return ResourceManager.GetString("Tooltip_ClearLiveLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Logs CSV 的本地化字符串。
        /// </summary>
        public static string Tooltip_ExportLogsCsv {
            get {
                return ResourceManager.GetString("Tooltip_ExportLogsCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Logs JSON 的本地化字符串。
        /// </summary>
        public static string Tooltip_ExportLogsJson {
            get {
                return ResourceManager.GetString("Tooltip_ExportLogsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Sessions CSV 的本地化字符串。
        /// </summary>
        public static string Tooltip_ExportSessionsCsv {
            get {
                return ResourceManager.GetString("Tooltip_ExportSessionsCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Tooltip_Home {
            get {
                return ResourceManager.GetString("Tooltip_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Tooltip_Refresh {
            get {
                return ResourceManager.GetString("Tooltip_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh Data 的本地化字符串。
        /// </summary>
        public static string Tooltip_RefreshData {
            get {
                return ResourceManager.GetString("Tooltip_RefreshData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh Hardware 的本地化字符串。
        /// </summary>
        public static string Tooltip_RefreshHardware {
            get {
                return ResourceManager.GetString("Tooltip_RefreshHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Tooltip_Settings {
            get {
                return ResourceManager.GetString("Tooltip_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Runtime 的本地化字符串。
        /// </summary>
        public static string Tooltip_StartRuntime {
            get {
                return ResourceManager.GetString("Tooltip_StartRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Runtime 的本地化字符串。
        /// </summary>
        public static string Tooltip_StopRuntime {
            get {
                return ResourceManager.GetString("Tooltip_StopRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Connection 的本地化字符串。
        /// </summary>
        public static string Tooltip_TestConnection {
            get {
                return ResourceManager.GetString("Tooltip_TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot reference itself as a sub-flow 的本地化字符串。
        /// </summary>
        public static string Validation_CannotReferenceSelfAsSubFlow {
            get {
                return ResourceManager.GetString("Validation_CannotReferenceSelfAsSubFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Circular reference detected through sub-flow &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        public static string Validation_CircularReferenceDetected {
            get {
                return ResourceManager.GetString("Validation_CircularReferenceDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller type is required 的本地化字符串。
        /// </summary>
        public static string Validation_ControllerTypeRequired {
            get {
                return ResourceManager.GetString("Validation_ControllerTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control profile is required 的本地化字符串。
        /// </summary>
        public static string Validation_ControlProfileRequired {
            get {
                return ResourceManager.GetString("Validation_ControlProfileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware category is required 的本地化字符串。
        /// </summary>
        public static string Validation_HardwareCategoryRequired {
            get {
                return ResourceManager.GetString("Validation_HardwareCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a hardware definition 的本地化字符串。
        /// </summary>
        public static string Validation_HardwareDefinitionRequired {
            get {
                return ResourceManager.GetString("Validation_HardwareDefinitionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid JSON in connection config 的本地化字符串。
        /// </summary>
        public static string Validation_InvalidConnectionConfigJson {
            get {
                return ResourceManager.GetString("Validation_InvalidConnectionConfigJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module name is required 的本地化字符串。
        /// </summary>
        public static string Validation_ModuleNameRequired {
            get {
                return ResourceManager.GetString("Validation_ModuleNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name is required 的本地化字符串。
        /// </summary>
        public static string Validation_NameRequired {
            get {
                return ResourceManager.GetString("Validation_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step &apos;{0}&apos; has invalid command parameters JSON 的本地化字符串。
        /// </summary>
        public static string Validation_StepInvalidCommandParametersJson {
            get {
                return ResourceManager.GetString("Validation_StepInvalidCommandParametersJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step &apos;{0}&apos; requires a hardware instance with a control profile 的本地化字符串。
        /// </summary>
        public static string Validation_StepRequiresHardwareInstanceWithProfile {
            get {
                return ResourceManager.GetString("Validation_StepRequiresHardwareInstanceWithProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vendor name is required 的本地化字符串。
        /// </summary>
        public static string Validation_VendorNameRequired {
            get {
                return ResourceManager.GetString("Validation_VendorNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow name is required 的本地化字符串。
        /// </summary>
        public static string Validation_WorkflowNameRequired {
            get {
                return ResourceManager.GetString("Validation_WorkflowNameRequired", resourceCulture);
            }
        }
    }
}
